FROM nginx:1.20.1-alpine

RUN curl https://download.karrot.world/karrot-frontend-production.zip -o karrot-frontend.zip && \
    unzip -o karrot-frontend.zip -d /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf